name: Location

author: Pello Altadill
website: http://pello.info
main: io.pello.mc.location.PlayerLocation

commands:
    location:
        description: Simple plugin to show player location
        usage: /location

version: 0.1